apiVersion: batch/v1
kind: Job
metadata:
  name: play
spec:
  template:
    spec:
      containers:
      - name: play
        image: busybox
        command: ["echo",  "1st flow complete"]
      restartPolicy: Never
      nodeSelector:
        kubernetes.io/os: linux
  backoffLimit: 1