from prefect import task, Flow
from prefect.tasks.kubernetes.job import CreateNamespacedJob
import yaml
from yaml import SafeLoader
from prefect.run_configs import KubernetesRun
from prefect.storage import GitHub
import requests


@task
def job1():
    url = 'https://raw.githubusercontent.com/miguelferrao/test-flow/0908802d9ac94a7ceb2a53c0ac344f9e288fffa1/flows/job.yaml'
    download = requests.get(url).content
    data = yaml.load(download, Loader=SafeLoader)
    CreateNamespacedJob(body=data, kubernetes_api_key_secret='ZXlKaGJHY2lPaUpTVXpJMU5pSXNJbXRwWkNJNkltWjVibHBRWjNOVmEzVnRYMlZJV0UxaWVFczBNbTR6YTJsMWJFOTRRMjlxZEVkMFlqbEZUVWt5UlUwaWZRLmV5SnBjM01pT2lKcmRXSmxjbTVsZEdWekwzTmxjblpwWTJWaFkyTnZkVzUwSWl3aWEzVmlaWEp1WlhSbGN5NXBieTl6WlhKMmFXTmxZV05qYjNWdWRDOXVZVzFsYzNCaFkyVWlPaUprWldaaGRXeDBJaXdpYTNWaVpYSnVaWFJsY3k1cGJ5OXpaWEoyYVdObFlXTmpiM1Z1ZEM5elpXTnlaWFF1Ym1GdFpTSTZJbVJsWm1GMWJIUXRkRzlyWlc0dGNuQm5abTRpTENKcmRXSmxjbTVsZEdWekxtbHZMM05sY25acFkyVmhZMk52ZFc1MEwzTmxjblpwWTJVdFlXTmpiM1Z1ZEM1dVlXMWxJam9pWkdWbVlYVnNkQ0lzSW10MVltVnlibVYwWlhNdWFXOHZjMlZ5ZG1salpXRmpZMjkxYm5RdmMyVnlkbWxqWlMxaFkyTnZkVzUwTG5WcFpDSTZJamt6WVRNeU9XVTVMVFZsTUdJdE5EQTNaQzA0TjJOakxUa3dOamd4TTJJMk5HSTNOQ0lzSW5OMVlpSTZJbk41YzNSbGJUcHpaWEoyYVdObFlXTmpiM1Z1ZERwa1pXWmhkV3gwT21SbFptRjFiSFFpZlEuWUsyand3bGpsMHVqTnN1SnN6bGpxM3FWbWF5ZW1BckNSeVk2VzM2eWtkYzR4dE9yS21EZEJxNTVfX0N2S2tCdkxzaWxQSk8ybTlubFU5STA3OEVrTEtUdzMyRkZwUVNJZ2I0X0xjYkNGZEltblhxQmItNmdUYWt0OElXZkJmMUVmTjQ3b1RETUdqSnVGbUM5NXRjakgwZ2R2d2FiOEZmSDNKRzd4RmR6THlIVW9YcktpWE5kRC1FSFZRb0htMzdpWjljTWNNb2FRRm5FZllCMG9VU3d3X25RZmRCY2VuOHpQUUhoTHJqNkhNanBXc0E3dF9FNktjU1VoWjdETUlJNDlkU2xDQ2NZTnhkRk5OQlhORkZib1pyR3BqS2ljOUFRa2FxSFppNTJvU0s1cnQ4dnJoUThRbUE2akVFVVZBSXp5NV9Cc1hZUTRJc2N1QldRT3hGTzNJdzdKVDVvOUVrb0MwaUZCZ2MyX3RhRmdmNUN3Z2dzR3h3blNmUFYtNGRfYlVaTUZfbUlNR3FaSFNlVkk2R0wyOThyMEpKZW1vOVowaEtuWFgzOVhTRDdoUUF3cUFpVkZCZzl2dkVBVTBBUlJ4ajlSZFRwUGMtNFlJNGIzMk5sUC04eW1jS0ZLc1h2TThNdFhQak9UdllMc1FnZkhUeGRVOVR5WUFDQmNsc1F1VnJvTlQwb0lhVHVhV1lOUlBWMUlPMjJ2WWcwdkNXWE9BZXBvQ0dkLV9wU2t0ekxGN3dqVHNzR0ktU1oyV2Q1WDM5SmJydmtBdHBGdXVEQTQxYkNLaThuUW5LaHNIRE9IWEJucEtZTThHTFZQcWtIQmJPSWRBZ21aREI1Yk5BSGVpMkdnNFdGVVlMRDNRT3RIZEtCSDdVRW85NFJZVWNYSUt4eEJuVnI2VTQ=').run()
    

with Flow(name="job-flow-1") as flow:
    task = job1()

flow.storage = GitHub(
    repo="miguelferrao/test-flow",
    path="k8s_job.py",       
)
